import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Tulga bna",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Bulga",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "ZARA bishee",
      category: "Үнэртэй ус",
      image: "/images/d1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "DO SON",
      category: "Үнэртэй ус",
      image: "/images/d2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "BON PARFUMER",
      category: "Үнэртэй ус",
      image: "/images/d3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "CHANEL №5",
      category: "Сайхан үнэртэй ус",
      image: "/images/d4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "CHANEL",
      category: "Сайхан үнэртэй ус",
      image: "/images/d5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "GIORGIO ARMANI",
      category: "Сайхан үнэртэй ус",
      image: "/images/d6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
